### ISSUE TITLE
It should stop meteor when Visual Studio Code is closed

### ISSUE THREAD

**Issue by tormodboga** [ramonitor/vscode-meteorhelper#1]
If you use MeteorHelper to start your app from within VS Code, and then later you close VS Code.. the meteor app is still running.. next time you start VS Code, it doesn't correctly reflect the status of the meteor app and if you try to run it again it will fail since the port is already open.

**Comment by ramonitor** [comment]
@tormodboga, I added this feature in the 0.1.2 release of the extension.

**Comment by tormodboga** [comment]
Great news, thank you! Love the extension...

/Tormod
