### ISSUE TITLE
No commands recognized since last update

### ISSUE THREAD

**Issue by DamonDeville** [ramonitor/vscode-meteorhelper#2]
get error message: `'meteorhelper.whatever' not found` after updating to last version.

**Comment by ramonitor** [comment]
Could you try to remove and reinstall the extension?

**Comment by Avijobo** [comment]
Same problem here... uninstalling and reinstalling does not solve it/

**Comment by DamonDeville** [comment]
Reinstalling reinstalls version 0.1.2 which generates the errors.
Thank God I had version 0.1.1 still installed on another machine. So I copied the extension folder from this other machine to my new machine and I am back in business.

**Comment by Avijobo** [comment]
I don't have an earlier version anymore... I hope it'll be fixed soon, because this is a really very helpful tool... 
Thanks in advance!

**Comment by ramonitor** [comment]
@DamonDeville, @Avijobo could you please try the new 0.1.3 release I just put out?

**Comment by DamonDeville** [comment]
It works! Thanks!

**Comment by tormodboga** [comment]
+1, works fine again now..
