### ISSUE TITLE
meteorhelper test mode: doesn't find Meteor.settings file

### ISSUE THREAD

**Issue by ArnieGA** [ramonitor/vscode-meteorhelper#4]
EDIT:
For some reason while running in test mode, meteorhelper is not finding the settings.json file specified in meteorhelper.meteorSettings.  It **does** find it when running the project, but not the tests:  all references to values inside that file make the tests crash (while they're loading).

Meteor version: 1.5
OS: Windows 10
VS Code version: 1.13.0

**Comment by ramonitor** [comment]
@ArnieGA, I'm curious what happens if you copy the command string that MeteorHelper shows in the output channel containing the syntax of the command being executed and paste that in your terminal. And are you using a meteorHelper.relativeProjectPath config in your workspace configuration?

**Comment by ArnieGA** [comment]
_And are you using a meteorHelper.relativeProjectPath config in your workspace configuration?_
Yes, I am.  I ended up changing the package.json file instead.
