### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by dobesv** [ramonitor/vscode-meteorhelper#6]
Some test drivers use environment variables for configuration, e.g. to test TEST_WATCH=1 to watch for changes and re-run tests in the console.

It would be great to be able to specify environment variables in the test configuration settings for this purpose.

**Comment by Neaox** [comment]
Any updates on this?

**Comment by ramonitor** [comment]
So you would like to be able to specify configuration (key/value pairs) on the MeteorHelper driverPackage entry in the vscode workspace configuration that, upon execution of 'meteor test' are added to process.env, right?

**Comment by ramonitor** [comment]
@dobesv, @Neaox, added this in MeteorHelper 0.1.4! See the documentation for an example on how to use the new functionality.
