### ISSUE TITLE
Specify --once

### ISSUE THREAD

**Issue by dobesv** [ramonitor/vscode-meteorhelper#7]
The test driver we are using just loops forever re-running the tests continuously if you don't use either `--once` or set the `TEST_WATCH=1` environment variable.  It would be nice to be able to specify that the `--once` option should be passed to `meteor test`.

Workaround: use a different test driver inside vscode.

**Comment by ramonitor** [comment]
@dobesv solved in 0.1.4 via environment variables! Please let me know if you have issues with the new version. Closing this one for now.
